"""
qrp_atlas.contracts - 全项目唯一字段/规则来源（SSOT）

contracts 成为全项目唯一字段/规则来源
CSV→清洗→入库→查询→可视化→回测 全都引用 contracts
避免未来"字段改一次，改一堆脚本"的灾难

模块说明：
- fields.py: 全项目字段名常量（SSOT）
- schema.py: 表结构（列清单 + 主键 + duckdb建表SQL）
- mappings.py: 各数据源字段映射（东财/AKShare/自有CSV等）
- conventions.py: 通用约定：日期格式、ticker规则、数值列集合等
- validate.py: 极简校验函数：缺列/多列/类型转换（MVP级）
"""

from .fields import (
    TICKER,
    TRADE_DATE,
    NAME,
    CREATED_AT,
    OPEN,
    HIGH,
    LOW,
    CLOSE,
    VOLUME,
    AMOUNT,
    PCT_CHANGE,
    PRE_CLOSE,
    TURNOVER,
    MARKET_CAP,
    FLOAT_CAP,
    IS_ST,
    IS_LIMIT_UP,
    IS_LIMIT_DOWN,
    PHASE,
    M1_CORE,
    M2_FRONT,
    M3_IDENTIFIABLE,
    V_TRIGGERED,
    NOTES,
    TRADE_ID,
    ENTRY_DATE,
    ENTRY_PRICE,
    PATH_TYPE,
    HALF_SELL_TRIGGER,
    HALF_SELL_DATE,
    HALF_SELL_PRICE,
    EXIT_DATE,
    EXIT_PRICE,
    POSITION_PCT,
    OHLCV_FIELDS,
    PRICE_FIELDS,
    NUMERIC_FIELDS,
    BOOLEAN_FIELDS,
    DATE_FIELDS,
    IDENTIFIER_FIELDS,
)

from .schema import (
    ColumnSpec,
    TableSchema,
    DAILY_MARKET_SNAPSHOT,
    MARKET_PHASE,
    TRADE_EXECUTION,
    ALL_TABLES,
    TABLE_BY_NAME,
    get_table,
    init_database,
)

from .mappings import (
    EASTMONEY_DAILY_BAR,
    EASTMONEY_SNAPSHOT,
    AKSHARE_DAILY_BAR,
    AKSHARE_REALTIME,
    SOURCE_MAPPINGS,
    get_mapping,
    apply_mapping,
    build_custom_mapping,
)

from .conventions import (
    DATE_FORMAT,
    DATE_FORMAT_COMPACT,
    DATETIME_FORMAT,
    TICKER_PATTERN,
    TICKER_LENGTH,
    SH_TICKER_PREFIXES,
    SZ_TICKER_PREFIXES,
    BJ_TICKER_PREFIXES,
    LIMIT_UP_PCT,
    LIMIT_UP_ST_PCT,
    LIMIT_DOWN_PCT,
    LIMIT_DOWN_ST_PCT,
    NUMERIC_DECIMAL_PLACES,
    NUMERIC_COLUMNS,
    BOOLEAN_COLUMNS,
    DATE_COLUMNS,
    STRING_COLUMNS,
    format_ticker,
    format_date,
    get_exchange,
    is_sh_ticker,
    is_sz_ticker,
    is_bj_ticker,
    calc_limit_up_pct,
    calc_limit_down_pct,
)

from .validate import (
    ValidationError,
    MissingColumnsError,
    ExtraColumnsError,
    TypeConversionError,
    check_missing_columns,
    check_extra_columns,
    validate_schema,
    convert_numeric,
    convert_boolean,
    convert_date,
    canonicalize,
    quick_validate,
)

__all__ = [
    "TICKER",
    "TRADE_DATE",
    "NAME",
    "CREATED_AT",
    "OPEN",
    "HIGH",
    "LOW",
    "CLOSE",
    "VOLUME",
    "AMOUNT",
    "PCT_CHANGE",
    "PRE_CLOSE",
    "TURNOVER",
    "MARKET_CAP",
    "FLOAT_CAP",
    "IS_ST",
    "IS_LIMIT_UP",
    "IS_LIMIT_DOWN",
    "PHASE",
    "M1_CORE",
    "M2_FRONT",
    "M3_IDENTIFIABLE",
    "V_TRIGGERED",
    "NOTES",
    "TRADE_ID",
    "ENTRY_DATE",
    "ENTRY_PRICE",
    "PATH_TYPE",
    "HALF_SELL_TRIGGER",
    "HALF_SELL_DATE",
    "HALF_SELL_PRICE",
    "EXIT_DATE",
    "EXIT_PRICE",
    "POSITION_PCT",
    "OHLCV_FIELDS",
    "PRICE_FIELDS",
    "NUMERIC_FIELDS",
    "BOOLEAN_FIELDS",
    "DATE_FIELDS",
    "IDENTIFIER_FIELDS",
    "ColumnSpec",
    "TableSchema",
    "DAILY_MARKET_SNAPSHOT",
    "MARKET_PHASE",
    "TRADE_EXECUTION",
    "ALL_TABLES",
    "TABLE_BY_NAME",
    "get_table",
    "init_database",
    "EASTMONEY_DAILY_BAR",
    "EASTMONEY_SNAPSHOT",
    "AKSHARE_DAILY_BAR",
    "AKSHARE_REALTIME",
    "SOURCE_MAPPINGS",
    "get_mapping",
    "apply_mapping",
    "build_custom_mapping",
    "DATE_FORMAT",
    "DATE_FORMAT_COMPACT",
    "DATETIME_FORMAT",
    "TICKER_PATTERN",
    "TICKER_LENGTH",
    "SH_TICKER_PREFIXES",
    "SZ_TICKER_PREFIXES",
    "BJ_TICKER_PREFIXES",
    "LIMIT_UP_PCT",
    "LIMIT_UP_ST_PCT",
    "LIMIT_DOWN_PCT",
    "LIMIT_DOWN_ST_PCT",
    "NUMERIC_DECIMAL_PLACES",
    "NUMERIC_COLUMNS",
    "BOOLEAN_COLUMNS",
    "DATE_COLUMNS",
    "STRING_COLUMNS",
    "format_ticker",
    "format_date",
    "get_exchange",
    "is_sh_ticker",
    "is_sz_ticker",
    "is_bj_ticker",
    "calc_limit_up_pct",
    "calc_limit_down_pct",
    "ValidationError",
    "MissingColumnsError",
    "ExtraColumnsError",
    "TypeConversionError",
    "check_missing_columns",
    "check_extra_columns",
    "validate_schema",
    "convert_numeric",
    "convert_boolean",
    "convert_date",
    "canonicalize",
    "quick_validate",
]
